### ISSUE TITLE
Todo list/roadmap

### ISSUE THREAD

**Issue by ogt** [ogt/webcommand-app#3]
## Minor Improvements
- [ ] Move the help text from bottom to top of the page
- [x] Make the < button to work (should be moving the output to the input)
- [x] Make the command text input a drop down that gets filled with the getCommands web service
- [x] Args should be passed as multi value parameter as opposed to spliting a single valued parameter  (as supported by the webcommand module)
- [x] Make the server code use the http://github.com/ogt/webcommand module
- [x] Make the client code similar to webcommand client code - or if you prefer use directly the webcommand module in index.html via browserify (see http://github.com/ogt/boxchareditor for an example of how to do that)
## Convert from sorter to generic command server
- [x] Derive the utility command to use from domain name (provide map domain name -> utility name, use xxxer whenever available) 
- [x] Refactor uses of sort in the sorter code to use the dynamically derived (from hostname) command. No mention should exist of the word sort.
- [x] If domain name is not in map, then the home page should be in a wrapper page that displays essentially the map ( utility name -> server's url ) as a table
- [x] add deployall shell script in the repo that iterates over map and 
  - creates heroku apps with corresponding name if app not exists and pushes the code there
  - do the same for the wrapper deploy `webcommandserver.herokuapp.com`
  - each app should have same owner's/collaborators as the github webcommand repos.
- [x] rename sorter repo to webcommandserver repo, have webcommandserver repo point to webcommandserver app
- [x] add generic readme for github repo
- [x] If domain is localhost) - allow overriding of utility name   `localhost:8000/sed?`  instead of `localhost:8000/?args..` for easier testing
- [x] add the browser command/arguments/input/output code in the wrapper page - but given there is no selected command display instead of the command name a drop-down with all commands. On execute we send the request to the correspond full url of the server for that command (as found from the map) - need to resolve cross site scripting issue
- [x] add makefile that drives man page scripts, deploy scripts, test scripts
- [ ] add man page generating script, which generates html versions of ubuntu man pages for all commands listed. Include link to the html page in the home page (in case of wrapper,  add the man page in the [command, server url, manpage] listing (check https://devcenter.heroku.com/articles/stack for heroku's os)
## Server-side piping
- [x] Allow one command to be able to pipe its output to another command instead of stdout. Add a pipe parameter (in addition to args that can take a list of webcommand urls as value [ 'greper.herokuapp.com/?foo', 'sorter.herokuapp.com/?args=-r']
- [x] Allow the use of where filename would be used. Webcommands before passing the arglists to the underlying unix command should check of an argument has the format of a url and in that case fetch the url in /tmp and replace the url with tmpname. after command execution delete that file.
- [x] Add 'cat' to the utility list
