### ISSUE TITLE
Todo List - Roadmap

### ISSUE THREAD

**Issue by ogt** [ogt/webcommand-app#9]
Presentation
- [ ] Fix the READMEs of webcommand/webcommand-app/webcommand-index
- [ ] Find how where to add manpage in the sites
- [ ] Fixup a bit the HTML/CSS of webcommand-app/webcommand-index
- [ ] Provide instruction -  free apps to sponsor webcommand services, may involve auto submit a pull request to add a service.

New Functionality
- [ ] Add URL -> filename auto-conversion
- [ ] Provide a reverse index - list of servers for each unix command, ordered by recent response time.
- [ ] get stderr to the HTTP error stream
- [x] Change UI - prefill http, ask for hostname only, fetch commands on update and fill-in dropdown
- [ ] Add a third param donotfetchurl if set urls are not converted
- [ ] Add a service that given a command gives back a server that serves the command
- [ ] Allow passing of command names - not just urls as pipes in which case a server is automatically found (if the command is not available locally)
- [ ] provide a command line command like rcat that would allow you to use web commands from the command line (similar to test command)
  assume like the symbols '][' "rcat xxx  ][ sort .... ][ grep ... etc .. which 

Testing
- [x] Add test for clocserverver, webcommand-app  (move the command specific tests from webcommand)
- [x] Add test for webcommand-express
- [x] Add pipe testing at  webcommand-express

Refactoring
- [x] Add at the webcommand level add a utility function that takes a wc {cmd : ..., args = [ ], pipes : [ { } { } ]} and converts it into a url and reverse 
- [x] rewrite webcommand-app to use webcommand-express
- [x] Refactor both server/clients to use it - use browserify to pull the library.
- [ ] Change webcommand-express tests to use promises and minimize replication of code
- [x] Fix cloc service - upgrade it to use webcommand
